# If true don't write to stdout or stderr
quiet: false
handlers:
    begin:
        - type: http
          config:
            uri: "http://conductor.service.owf-dev:xxx/api/tasks/poll/${meta.taskType}"
            method: "GET"
          # Additional context to add from the response of the call to be made available to other
          # phases in the lifecycle.
          context: [ "taskId" ]
    #progress:
    completed:
        - type: http
          config:
            uri: "http://conductor.service.owf-dev"
            method: "POST"
            # See Event struct in lifecycle/handler.go for available fields in the body section
            body: |
                '{
                    "workflowInstanceId": "${meta.workflowInstanceId}",
                    "taskId": "${meta.taskId}",
                    "callbackAfterSeconds": 0,
                    "status": "COMPLETED",
                    "outputData": {}
                }'
    failed:
        - type: http
          config:
            uri: "http://conductor.service.owf-dev"
            method: "POST"
            body: |
                '{
                    "workflowInstanceId": "${meta.workflowInstanceId}",
                    "taskId": "${meta.taskId}",
                    "reasonForIncompletion": "Exited with code: ${data}",
                    "callbackAfterSeconds": 0,
                    "status": "FAILED",
                    "outputData": {"exitCode": ${data}}
                }'
