# Required metadata keys that need to supplied at runtime.  If specified floop will check these are
# defined before starting the child process.
meta:
- taskType # NoMadeUpdateTask1
- workflowInstanceId # 8fecc7dd-9736-43f1-983b-30f8e1cb6de3

# command: docker
# args: [
#   "run", "--rm",
#   "opencoconut/ffmpeg", "-progress", "/dev/stdout",
#   "-i", "http://files.coconut.co.s3.amazonaws.com/test.mp4",
#   "-f", "webm", "-c:v", "libvpx", "-c:a", "libvorbis",
#   "test.webm" ]


# If true don't write to stdout or stderr
quiet: true

# Handler configuration for each lifecycle phase
handlers:
  # Called before the child process is launched
  begin:
  - type: http
    # Continue launching child process even if handler call returns an error.  Comment this
    # out to exit w/o launching the child process on handler failure
    #ignorerrors: true
    config:
      uri: "http://conductor-server.service.owf-dev:30000/api/tasks/poll/${meta.taskType}"
      method: "GET"
    # Additional context to add from the response of the above call which is made available
    # during phases of the lifecycle after this one.
    context: [ "taskId" ]
  # Called any time child process flushes data to stdout and stderr
  progress:
  - type: echo
    # Transform the event data (i.e. from stdout/stderr) into key-values before issueing the
    # callback. If floop fails to apply the transform, the event will contain raw data.
    transform: [ "kv", "\n", "=" ]
  # Called when a process exits with a zero status
  completed:
  - type: http
    config:
      uri: "http://conductor-server.service.owf-dev:30000/api/tasks"
      method: "POST"
      headers:
        Content-Type: "application/json"
      # See types.Event struct for available fields
      body: |
        {
            "workflowInstanceId": "${meta.workflowInstanceId}",
            "taskId": "${meta.taskId}",
            "reasonForIncompletion": "",
            "callbackAfterSeconds": 0,
            "status": "COMPLETED",
            "outputData": {}
        }
  # Called when the process exits with a non-zero status
  failed:
  - type: http
    config:
      uri: "http://conductor-server.service.owf-dev:30000/api/tasks"
      method: "POST"
      headers:
        Content-Type: "application/json"
      body: |
        {
            "workflowInstanceId": "${meta.workflowInstanceId}",
            "taskId": "${meta.taskId}",
            "reasonForIncompletion": "Exited with code: ${data}",
            "callbackAfterSeconds": 0,
            "status": "FAILED",
            "outputData": {"exitCode": ${data}}
        }
